### ISSUE TITLE
How can I add tls and basic_auth ?

### ISSUE THREAD

**Issue by itning** [czerwonk/ping_exporter#124]
in node_exporter, I can use this command to enable tls and basic auth.
`./node_exporter --web.config.file=web-config.yml`

[web-config.yml](https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md)
```yml
tls_server_config:
  cert_file: /root/node_exporter/fullchain.cer
  key_file: /root/node_exporter/xxx.key
basic_auth_users:
  username: xxx
```
so how can I add tls and basic_auth ?
