### ISSUE TITLE
New version stopped working

### ISSUE THREAD

**Issue by j2ghz** [czerwonk/ping_exporter#19]
I have been running with this simple config for a few months

docker-compose.yml:
```yaml
  ping-exporter:
    volumes:
      - ./config:/config:ro
    image: czerwonk/ping_exporter
```
config
```yml
targets:
  - 1.1.1.1
  - 192.168.1.1
```
Since an update on 6.2.2019 the container exits with:
```
ping_exporter: error: ping.history-size must be greater than 0
usage: ping_exporter [<flags>] [<targets>...]
...
```
Since I'm not specifying the history size anywhere, I assume it has default value. Does that mean that the default value is 0? Could it be changed to a sensible default so that it works without the need to specify? Also, the readme examples do not mention this.
