### ISSUE TITLE
Prometheus config example

### ISSUE THREAD

**Issue by zacho112** [czerwonk/ping_exporter#39]
Hi,

I'm not quite sure how to setup Prometheus, do you guys have a example config?

Thanks

**Comment by dmke** [comment]
Assuming both Prometheus and the `ping_exporter` run on the same host:

1. Create a config file for `ping_exporter`, as described in the README. Save it as `/etc/ping_exporter/config.yml`.
2. Start `ping_exporter --config /etc/ping_exporter/config.yml`.
3. Add the following snippet to your Prometheus scrape config:

    ```yaml
    scrape_configs:
      # ... other jobs ...
      - job_name: ping
        static_configs:
          - targets:
            - 127.0.0.1:9427
    ```

4. Restart Prometheus.

If the `ping_exporter` runs on a different host (say `ping.example.com`), you need:

1. Ensure `http://ping.example.com:9427/metrics` is reachable from the host running Prometheus.
2. Substitute `127.0.0.1:9427` for `ping.example.com:9427` in the Prometheus config.
