### ISSUE TITLE
Updating to v0.4.8 Caused Loss of Connectivity

### ISSUE THREAD

**Issue by cassidy3** [czerwonk/ping_exporter#63]
Hello,
We're using `ping_exporter` in a limited capacity to test uptime to certain equipment. The software runs in a container through Docker Swarm Mode and, after the update from v0.4.7 to v0.4.8, connectivity was lost. `ping_exporter` did not provide metrics for the devices it was pinging, but it did continue to provide its own status. From Grafana, through Prometheus, it looked like this:

![2021-12-10 Ping Exporter](https://user-images.githubusercontent.com/15707989/145607791-bc1fdb2a-ff75-417b-89e3-7fc85e43d611.png)

The yellow and green show the ping_up metric. Green is v0.4.7 and yellow is v0.4.8. As you can see, for the time it ran on v0.4.8, the other metrics were not provided to Prometheus. The instant we swapped back to v0.4.7, these metrics began logging again. No configuration change was made between updates - the only that changed was the version number in the compose file. No log lines were generated in `ping_exporter`'s logs.

Here's our running config:

```yaml
# ping_exporter/config.yml
targets:
  - "[REDACTED IP]"
  - "[REDACTED IP]"
  - "[REDACTED IP]"
  - "[REDACTED IP]"
dns:
  refresh: 30m
  nameserver: [REDACTED IP]
ping:
  interval: 5s
  timeout: 2s
  history-size: 100
  payload-size: 10
```

This is obviously non-urgent as we're fine with running v0.4.7 for the time being. Please let me know if we can provide any additonal information to help you troubleshoot, and thank you for making such a handy tool.

**Comment by soapiestwaffles** [comment]
@cassidy3 I've been running 0.4.8 and can't reproduce this. Can you paste your config that you're using and the command line parameters you are using?

**Comment by cassidy3** [comment]
Absolutely. It *was* starting mind you, but it was just generating the same logs it usually does (letting us know it's running on v0.4.8). No errors, warnings, etc. I'll be onsite tomorrow so I'm happy to attempt the upgrade again in the morning and provide the output. 

We don't use any additional command line parameters, so it should be using the image default (`/bin/sh -c ./ping_exporter --config.path $CONFIG_FILE`). Also, it's in Docker Swarm Mode, so it should have several network interfaces - local, ingress, plus the two user-provided networks (`backend` - isolated but contains ping targets, `database` - entirely isolated and can only link between prometheus and `ping_exporter`). It works great with this config on v0.4.7.

Anyway, here are our config files:

```yaml
# ping_exporter/config.yml
targets:
  - "[REDACTED IP]"
  - "[REDACTED IP]"
  - "[REDACTED IP]"
  - "[REDACTED IP]"
dns:
  refresh: 30m
  nameserver: [REDACTED IP]
ping:
  interval: 5s
  timeout: 2s
  history-size: 100
  payload-size: 10
  ```
  
  ```yaml
  # prometheus/config.yml
  scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'uptime'
    static_configs:
    - targets: ['uptime:9427']
  ...more scrape targets...
  ```
  
  ```yaml
  # deploy/stack-monitoring.yml
  version: "3.8"
  services:
    prometheus:
      image: prom/prometheus:v2.31.1
      hostname: prometheus
      networks:
        - database
        - backend
      volumes:
        - prometheus_conf:/etc/prometheus
        - prometheus_data:/prometheus
      command: '--storage.tsdb.retention.time=1y --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles'
      deploy:
        replicas: 1
        placement:
          constraints:
            - node.platform.os == linux
        restart_policy:
          condition: on-failure

    uptime:
      image: czerwonk/ping_exporter:v0.4.8
      hostname: uptime
      networks:
        - backend
        - database
      volumes:
        - prometheus_conf:/config:ro
      deploy:
        replicas: 1
        placement:
          constraints:
            - node.platform.os == linux
        restart_policy:
          condition: on-failure

networks:
  backend:
    external: true
  database:
    external: true

volumes:
  prometheus_conf:
    external: true
  prometheus_data:
    external: true
```
