### ISSUE TITLE
ping_loss_ratio averaging concern/question.

### ISSUE THREAD

**Issue by Randommmm** [czerwonk/ping_exporter#93]
Hi all, 

I'm running a configuration which uses ping_exporter to query a range of services (primarily devices within our network and VoIP phone provider) for packet loss via the ping_loss_ratio metric. 

We've had packet loss issues for a while now, although the data I am getting into Prometheus (and then Grafana) seems to be slightly incorrect. 

I notice the packet loss numbers seems very simalir, for example, I only seem to be getting data values of 2.38%, 4.76% 7.14%, 9.52%, etc. These numbers are NOT random, they seem to be averaged somehow. For example, 2.38*2 = 4.76, 4.76*2 = 9.52, they seem to be multiples somehow. This data is represented within both Grafana and Promethues. 

<img width="455" alt="Screenshot 2023-11-06 at 9 59 43 AM" src="https://github.com/czerwonk/ping_exporter/assets/33863649/3205259b-9e7a-4e11-bf3a-f04d466ad643">
<img width="792" alt="Screenshot 2023-11-06 at 10 00 09 AM" src="https://github.com/czerwonk/ping_exporter/assets/33863649/d12cd613-b68a-4114-bdf4-5828ce470e8c">

I use the following settings within the prometheus.yml file. 

```
- job_name: ping_exporter
  honor_timestamps: true
  scrape_interval: 1s
  scrape_timeout: 1s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 10.20.60.11:9427
```

What could I be doing wrong to get somewhat malformed data? 

Cheers, 
Lachlan.
